---
Metrics/BlockLength:
  Exclude:
    - spec/**/*

Naming/FileName:
  Exclude:
    - lib/nextcloud-deck-api.rb
    - spec/nextcloud-deck-api_spec.rb

# TODO: reenable later
Style/Documentation:
  Enabled: false

Style/WordArray:
  Enabled: false
